name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-tools
        run: pip install pip-tools
      - name: Compile requirements.txt
        run: pip-compile requirements.in
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install pytest
      - name: Install package in editable mode
        run: pip install -e .
      - name: Run tests
        run: pytest
